version: "2"
services:
  php:
    build: 
        context: .
        dockerfile: Dockerfile.php
    networks:
      - lnmp
    volumes:
       -  ./web:/web
    environment: 
      - TZ=Asia/Shanghai
  httpd:
    image: httpd:2.4.33
    networks:
      - lnmp
    environment:
      - TZ=Asia/Shanghai
  nginx:
    image: nginx:latest
    networks:
      - lnmp
    ports:
      - 80:80
    volumes:
      - ./web:/web
      - ./nginx:/etc/nginx
      - ./nginx/logs:/etc/nginx/logs
    environment: 
      - TZ=Asia/Shanghai
    links:
      - php
      - httpd
  mysql:
    hostname: mysql
    image: mysql:5.6
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    networks:
      - lnmp
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
networks:
  lnmp:
